mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db_name: chat
  username: root
  password: 051102ydq
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: info
zap:
    level: debug
    filename: ./gochat.log
    max_size: 200
    max_backups: 30
    max_age: 5
    is_console_print: true